# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9218b1420ccc51d7df17e49c482287554e5b063f4c24990c617d3680eb880dd1a29e18b3444abd00694dee547f5481d5baa06959de8c8a96cb1fd5ca7282a2c6

test:
  secret_key_base: 06739b30843835ac0d6fd5a3804dbf8605eafa4d1e761ba9413206dc3188150cc26b632c975e677faa14d6ba44b2fc4022f689bd505ce247b15ef6a3c8a780c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
